# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 13:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactstornco',
            options={'verbose_name': 'Stornco Contact', 'verbose_name_plural': 'Stornco Contacts'},
        ),
        migrations.AddField(
            model_name='contactstornco',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
