# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Echo',
            new_name='Hello',
        ),
        migrations.AlterModelOptions(
            name='hello',
            options={'verbose_name': 'Hello', 'verbose_name_plural': 'Hellos'},
        ),
    ]
