# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shape', models.CharField(choices=[('r', 'Rectangular'), ('t', 'Triangular')], max_length=1)),
                ('base', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pitch', models.DecimalField(decimal_places=1, max_digits=3)),
                ('aspect', models.DecimalField(decimal_places=1, max_digits=3)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9)),
            ],
        ),
    ]
