# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 02:33
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roof', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roof',
            name='aspect',
            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(limit_value=Decimal('0'), message='Aspect cannot be less than zero degrees.'), django.core.validators.MaxValueValidator(limit_value=Decimal('360'), message='Aspect cannot exceed 360 degrees.')]),
        ),
        migrations.AlterField(
            model_name='roof',
            name='base',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(limit_value=Decimal('0'), message='Base measurement cannot be less than zero meters.'), django.core.validators.MaxValueValidator(limit_value=Decimal('999.99'), message='Base measurement cannot exceed 999.99 meters.')]),
        ),
        migrations.AlterField(
            model_name='roof',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(limit_value=Decimal('0'), message='Height cannot be less than zero meters.'), django.core.validators.MaxValueValidator(limit_value=Decimal('99.99'), message='Height measurement cannot exceed 99.99 meters.')]),
        ),
        migrations.AlterField(
            model_name='roof',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=9, validators=[django.core.validators.MinValueValidator(limit_value=Decimal('-90'), message='Latitude may not be less than -90 degrees.'), django.core.validators.MaxValueValidator(limit_value=Decimal('90'), message='Latitude may not exceed 90 degrees.')]),
        ),
        migrations.AlterField(
            model_name='roof',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(limit_value=Decimal('-180'), message='Longitude cannot be less than -180 degrees.'), django.core.validators.MaxValueValidator(limit_value=Decimal('180'), message='Longitude cannot exceed 180 degrees.')]),
        ),
        migrations.AlterField(
            model_name='roof',
            name='pitch',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(limit_value=Decimal('0'), message='Pitch cannot be less than zero degrees.'), django.core.validators.MaxValueValidator(limit_value=Decimal('75'), message='Pitch cannot exceed 75 degrees.')]),
        ),
    ]
